project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bennysun1
format:
  html:
    theme: yeti
    css: styles.css



